title: 하루의 마무리
email: yoonsj913@gmail.com
description: 기록
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ysj13.github.io" # the base hostname & protocol for your site
postCount: 5 # the number of posts on the "index" page

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
